# permissions for end users to view k6s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k6-operator
    app.kubernetes.io/managed-by: kustomize
  name: k6-viewer-role
rules:
- apiGroups:
  - k6.io
  resources:
  - k6s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k6.io
  resources:
  - k6s/status
  verbs:
  - get
